service: star-wars-api
frameworkVersion: '3'

plugins:
  - serverless-localstack

custom:
  dynamoTableName: 'star_wars_table'
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ starWarsTable, Arn ]
  apiGateway:
    restApiId:
      Ref: ApiGatewayRestApi
    restApiRootResourceId:
      Fn::GetAtt: [ ApiGatewayRestApi, RootResourceId ]

functions:
  fn_star_wars_get:
    handler: fn_star_wars_get/src/index.handler
    description: Lambda to get resources from API star wars
    memorySize: 128
    timeout: 10
    environment:
      URL_SWAPI: "https://swapi.py4e.com/api"
      DYNAMO_REGION: "us-east-1"
      DEFAULT_PAGINATION_ITEMS: "20"
      AXIOS_DEFAULT_TIME: "7000"
      STAR_WARS_TABLE_DB: ${self:custom.dynamoTableName}
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    package:
      individually: true
      artifact: build/fn_star_wars_get/fn_star_wars_get.zip
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /people
          method: get
          cors: true
      - http:
          path: /people/{personId}
          method: get
          cors: true
      - http:
          path: /films
          method: get
          cors: true
      - http:
          path: /films/{filmId}
          method: get
          cors: true

resources:
  Resources:
    starWarsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: schema_name
            AttributeType: S
          - AttributeName: object_id
            AttributeType: S
        KeySchema:
          - AttributeName: schema_name
            KeyType: HASH
          - AttributeName: object_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.dynamoTableName}

    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: star_wars_api
